####################################
#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      discovery:
#        enabled: true
#      server:
#        git:
#          uri: https://github.com/tzs919/config.git
#          searchPaths: cargoservice,customerservice
#          username: tzs919
#          password: 123456


####################################
server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       discovery:
         enabled: true
       server:
         native:
#              searchLocations: file://
           searchLocations: classpath:config/cargoservice,classpath:config/customerservice
